# Generated by Django 4.2.3 on 2024-02-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_saiyoai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementsuggestion',
            name='styled_job_ticket_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementsuggestion',
            name='styled_scout_text_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='improvementsuggestion',
            name='styled_story_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
