# Generated by Django 4.2.3 on 2024-02-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_saiyoai', '0002_improvementsuggestion_styled_job_ticket_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementsuggestion',
            name='word_limit',
            field=models.IntegerField(default=500),
        ),
    ]
