# Generated by Django 4.2.3 on 2024-02-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_saiyoai', '0003_improvementsuggestion_word_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementsuggestion',
            name='user_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
