# Generated by Django 4.2.3 on 2024-02-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_saiyoai', '0004_improvementsuggestion_user_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementsuggestion',
            name='dall_e_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
