# Generated by Django 4.2.3 on 2024-03-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_saiyoai', '0008_conversation_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementsuggestion',
            name='job_posting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improvement_suggestions', to='my_saiyoai.jobposting'),
        ),
    ]
